title: "COCO-ReM"
subtitle: "Benchmarking Detectors with COCO: A New Path Forward"
url: "https://cocorem.xyz"

# Build settings
include: ["_pages"]
plugins_dir:
  - jekyll-sitemap

sass:
  style: "compressed"
  sass_dir: "static/css"

# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

exclude:
  - explore-app
  - vendor
